from enum import Enum

class Card(Enum):
    MYSTERY = '?'
    MAX0 = 'MAX0'
    NEG10 = '-10'
    NEG5 = '-5'
    ZERO = '0'
    ONE = '1'
    TWO = '2'
    THREE = '3'
    FOUR = '4'
    FIVE = '5'
    SIX = '6'
    SEVEN = '7'
    EIGHT = '8'
    NINE = '9'
    TEN = '10'
    FIFTEEN = '15'
    TWENTY = '20'